<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>    
    <!-- <PublishTrimmed>true</PublishTrimmed> -->
    <!-- <RestoreSources>$(RestoreSources);../../NodeHostEnvironment/bin/Debug;../../ElectronHostedBlazor/bin/Debug;https://api.nuget.org/v3/index.json</RestoreSources> -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ElectronHostedBlazor\ElectronHostedBlazor.csproj" />
  </ItemGroup>

</Project>
